# Generated by Django 4.1.2 on 2022-10-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0002_alter_model1_options_model1_pole2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole1', models.CharField(max_length=45)),
                ('pole2', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.RemoveField(
            model_name='model1',
            name='pole2',
        ),
    ]
