# Generated by Django 4.1.2 on 2022-10-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0004_model2_pole3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model2',
            name='pole2',
        ),
    ]
