# Generated by Django 4.1.2 on 2022-10-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0006_model2_pole2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model2',
        ),
        migrations.AlterModelOptions(
            name='model1',
            options={},
        ),
        migrations.AddField(
            model_name='model1',
            name='pole2',
            field=models.CharField(default=12, max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='model1',
            name='pole1',
            field=models.IntegerField(),
        ),
    ]
