# Generated by Django 4.1.2 on 2022-10-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0007_delete_model2_alter_model1_options_model1_pole2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole1', models.CharField(max_length=45)),
                ('pole2', models.IntegerField()),
                ('pole3', models.TextField()),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.AlterModelOptions(
            name='model1',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.RemoveField(
            model_name='model1',
            name='pole2',
        ),
        migrations.AlterField(
            model_name='model1',
            name='pole1',
            field=models.CharField(max_length=45),
        ),
    ]
